/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:271f8f12-741a-4e4a-a713-de71e1421a89",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_8qN987MaS",
    "aws_user_pools_web_client_id": "3nam9sc9bljb2e5n6rd54m04sa",
    "oauth": {}
};


export default awsmobile;
