/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:c33a019a-ff42-45a1-bbbf-63af63c07244",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_WxYEz8iEH",
    "aws_user_pools_web_client_id": "35uif9e8580r94u9vpdcrmim2g",
    "oauth": {},
    "aws_user_files_s3_bucket": "bicompare151541-dev",
    "aws_user_files_s3_bucket_region": "us-east-1"
};


export default awsmobile;
